---
title: "Clinical data report"
output:
  html_document:
    df_print: paged
---

```{r message=FALSE, include=FALSE}
#load libraries and data
library(tidyverse)
library(ggpubr)

db <- data.table::fread("C:/Users/emat/Alma Mater Studiorum Università di Bologna/PROJECT 1q & 13 - Documenti/complete_database_1q_13_181019.txt", encoding = 'UTF-8')

```

____

### Protocol

```{r}

db$PROTOCOL %>% table
db$PROTOCOL[!(db$PROTOCOL %in% c("BO2005","EMN02","AMB"))] <- "AMB" 
db$PROTOCOL %>% table
```


```{r}

db_young <- db %>% filter( Age <= 65)

```



```{r}
db_num_vars <- db_young %>% select(beta2m, Age, Albumin, Creatinine, HB, PLTs, Tot_PC, LDH, Calcium)

db_cat_vars <- db_young %>% select(Sex, Tx_yes_no, Tx_number, MANTEINANCE, CONSOLIDATION, HB_m_105, plt_m_150, PC_60_01,ISS,IgH_isotype, `K/L`,PROTOCOL, FISH_del_17p, t_4_14)

```


```{r message=FALSE, warning=FALSE, results='asis'}

num_vars = (names(db_num_vars))


i= num_vars[8]

data_frame_res <- list()


for(i in num_vars){

print(i)
  
i <- as.symbol(i)
  
sum <- cbind(as.character(i), db_young %>% group_by(PROTOCOL) %>% summarise(count=n(), 
                                                     mean=mean(!!i %>% as.numeric(), na.rm=T), 
                                                     sd=sd(!!i %>% as.numeric(), na.rm=T)))

sum


# db_young %>% ggplot(aes(Age, group=PROTOCOL, colour=PROTOCOL)) + geom_density()

# p1 <- ggboxplot(db_young, "PROTOCOL", as.character(i), color="PROTOCOL")
# p2 <- ggline(db_young, "PROTOCOL", as.character(i), color="PROTOCOL", add = c("mean_se", "jitter"))
# print(ggarrange(p1,p2))


res.aov <- aov(as.formula(paste(i, "~ PROTOCOL")), data = db_young)
p.val <- summary(res.aov)[[1]][["Pr(>F)"]][1]

record <- c(as.character(i), sum$mean %>% round(3), p.val %>% round(5)) 

record

data_frame_res[[i]] <- record

}

data_frame_res <- as.data.frame(data_frame_res) %>% as.matrix() %>% t

colnames(data_frame_res) <-  c("variable","AMB","BO2005","EMN02","p-value")

```


```{r}

write_tsv(data_frame_res %>% as.data.frame(), "clipboard")

```


```{r}


db_cat_vars$TX_1vs2 <- ifelse(db_cat_vars$Tx_number==2,"doubleTX", ifelse(db_cat_vars$Tx_number==1, "singleTX", NA) )

db_cat_vars$IgH_isotype %>% unique()
db_cat_vars$IgG <- ifelse(db_cat_vars$IgH_isotype=="IgG",1, ifelse(!is.na(db_cat_vars$IgH_isotype), 0, NA) )
db_cat_vars$IgM <- ifelse(db_cat_vars$IgH_isotype=="IgM",1, ifelse(!is.na(db_cat_vars$IgH_isotype), 0, NA) )
db_cat_vars$IgD <- ifelse(db_cat_vars$IgH_isotype=="IgD",1, ifelse(!is.na(db_cat_vars$IgH_isotype), 0, NA) )
db_cat_vars$IgA <- ifelse(db_cat_vars$IgH_isotype=="IgA",1, ifelse(!is.na(db_cat_vars$IgH_isotype), 0, NA) )
db_cat_vars$BJ <- ifelse(db_cat_vars$IgH_isotype=="BJ",1, ifelse(!is.na(db_cat_vars$IgH_isotype), 0, NA) )


db_cat_vars$ISS %>% unique()
db_cat_vars$ISS_1 <- ifelse(db_cat_vars$ISS==1,1, ifelse(!is.na(db_cat_vars$IgH_isotype), 0, NA) )
db_cat_vars$ISS_2 <- ifelse(db_cat_vars$ISS==2,1, ifelse(!is.na(db_cat_vars$IgH_isotype), 0, NA) )
db_cat_vars$ISS_3 <- ifelse(db_cat_vars$ISS==3,1, ifelse(!is.na(db_cat_vars$IgH_isotype), 0, NA) )


# db_cat_vars$IgG %>% table(useNA="always")

cat_vars = (names(db_cat_vars))
cat_vars


i=13

res_df_cat <- data.frame()

for(i in c(13:23)){
  
print(i)
  
name <- cat_vars[i]
name
  
model <- gmodels::CrossTable(db_cat_vars$PROTOCOL, db_cat_vars[[i]], fisher = T)

p.val <- model$fisher.ts$p.value %>% round(4)
p.val

res <- model$t %>% t %>% as.data.frame.matrix() %>% rownames_to_column()
res2<- cbind(name,res,p.val)

res2

res_df_cat <- rbind(res_df_cat, res2)

}


```

```{r}
write_tsv(res_df_cat, "clipboard")
```




______ SURVIVAL ANALYSYS ________

```{r}

library(survival)
library(survminer)

OS <- Surv( time = db_young$OS_months, event = db_young$OS_event_death)

PFS <- Surv( time = db_young$PFS_I_months, event = db_young$PFS_I_event)


```


OS
```{r}
  ggsurvplot(survfit(OS ~ db_young$CONS_1_0, data = db_young), pval = T, risk.table = T, xlab = "OS")

coxph(OS ~ db_young$CONS_1_0, data = db_young) %>% summary

```

PFS
```{r}
ggsurvplot(survfit(PFS ~ db_young$CONS_1_0, data = db_young), pval = T, risk.table = T, xlab = "PFS")

coxph(OS ~ db_young$CONS_1_0, data = db_young) %>% summary

```
```{r}





```

