---
title: "Clinical data report"
output:
  html_document:
    df_print: paged
---

```{r message=FALSE, include=FALSE}
#load libraries and data
library(tidyverse)
library(data.table)
library(ggpubr)

```

____

```{r}
import <- fread("C:/Users/mm_gr/Alma Mater Studiorum Università di Bologna/PROJECT 1q & 13 - Documenti/complete_database_1q_13_181019.txt")


import$PROTOCOL %>% table
import$PROTOCOL[!(import$PROTOCOL %in% c("BO2005","EMN02","AMB"))] <- "AMB" 
import$PROTOCOL %>% table
```


```{r}
# define the MM risk label from commpass broad + focal CNAs
import$AMP_1q_genes_all <- with(import, 
                                    ifelse(`AMP_maj_focal_ANP32E`==1 | `AMP_maj_focal_MCL1` ==1 | `AMP_maj_focal_CKS1B`==1, 1,0 ))
    
    
table(import$`AMP_maj_broad_chr_1q`, import$AMP_1q_genes_all)
table(import$`DEL_maj_broad_chr_13q`, import$`DEL_maj_focal_RB1`)


import$MMrisk_1q_all <- ifelse( import$`AMP_maj_broad_chr_1q` == 1 | import$AMP_1q_genes_all ==1, 1, 0)
import$MMrisk_13_all <- ifelse( import$`DEL_maj_broad_chr_13q` ==1 | import$`DEL_maj_focal_RB1` ==1, 1, 0)

import$MMrisk_CLASSIFIER_ALL <- 3  - import$MMrisk_1q_all - import$MMrisk_13_all
import$MMrisk_CLASSIFIER_ALL <- dplyr::recode(as.character(import$MMrisk_CLASSIFIER_ALL), "1"="risk1","2"="risk2","3"="risk3")

table(import$MMrisk_CLASSIFIER_ALL)
```


```{r}
db_num_vars <- import %>% select(beta2m, Age, Albumin, Creatinine, HB, PLTs, Tot_PC, LDH, Calcium)

db_cat_vars <- import %>% select(Sex, Tx_yes_no, Tx_number, MANTEINANCE, CONSOLIDATION, HB_m_105, plt_m_150, PC_60_01,ISS,IgH_isotype, `K/L`, PROTOCOL, MMrisk_CLASSIFIER_ALL)

```


Loop per numeric variables
```{r message=FALSE, warning=FALSE, results='asis'}

num_vars = (names(db_num_vars))


i= num_vars[9]

data_frame_res <- list()


for(i in num_vars){

print(i)
  
i <- as.symbol(i)
  
sum <- cbind(as.character(i), import %>% group_by(MMrisk_CLASSIFIER_ALL) %>% summarise(count=n(), 
                                                     mean=mean(!!i %>% as.numeric(), na.rm=T), 
                                                     sd=sd(!!i %>% as.numeric(), na.rm=T)))

sum


import %>% ggplot(aes(PLTs, group=MMrisk_CLASSIFIER_ALL, colour=MMrisk_CLASSIFIER_ALL)) + geom_density()

 # p1 <- ggboxplot(import, "MMrisk_CLASSIFIER_ALL", as.character(i), color="MMrisk_CLASSIFIER_ALL")
 # p2 <- ggline(import, "MMrisk_CLASSIFIER_ALL", as.character(i), color="MMrisk_CLASSIFIER_ALL", add = c("mean_se", "jitter"))
 # print(ggarrange(p1,p2))


res.aov <- aov(as.formula(paste(i, "~ MMrisk_CLASSIFIER_ALL")), data = import)
p.val <- summary(res.aov)[[1]][["Pr(>F)"]][1]

record <- c(as.character(i), sum$mean %>% round(3), p.val %>% round(5)) 

record

data_frame_res[[i]] <- record

}

data_frame_res <- as.data.frame(data_frame_res) %>% as.matrix() %>% t

colnames(data_frame_res) <-  c("variable","risk1","risk2","risk3","p-value")

```


```{r}

write_tsv(data_frame_res %>% as.data.frame(), "clipboard")

```


CATEGORICAL VARIABLES

```{r}


db_cat_vars$TX_1vs2 <- ifelse(db_cat_vars$Tx_number==2,"doubleTX", ifelse(db_cat_vars$Tx_number==1, "singleTX", NA) )

db_cat_vars$IgH_isotype %>% unique()
db_cat_vars$IgG <- ifelse(db_cat_vars$IgH_isotype=="IgG",1, ifelse(!is.na(db_cat_vars$IgH_isotype), 0, NA) )
db_cat_vars$IgM <- ifelse(db_cat_vars$IgH_isotype=="IgM",1, ifelse(!is.na(db_cat_vars$IgH_isotype), 0, NA) )
db_cat_vars$IgD <- ifelse(db_cat_vars$IgH_isotype=="IgD",1, ifelse(!is.na(db_cat_vars$IgH_isotype), 0, NA) )
db_cat_vars$IgA <- ifelse(db_cat_vars$IgH_isotype=="IgA",1, ifelse(!is.na(db_cat_vars$IgH_isotype), 0, NA) )
db_cat_vars$BJ <- ifelse(db_cat_vars$IgH_isotype=="BJ",1, ifelse(!is.na(db_cat_vars$IgH_isotype), 0, NA) )


db_cat_vars$ISS %>% unique()
db_cat_vars$ISS_1 <- ifelse(db_cat_vars$ISS==1,1, ifelse(!is.na(db_cat_vars$ISS), 0, NA) )
db_cat_vars$ISS_2 <- ifelse(db_cat_vars$ISS==2,1, ifelse(!is.na(db_cat_vars$ISS), 0, NA) )
db_cat_vars$ISS_3 <- ifelse(db_cat_vars$ISS==3,1, ifelse(!is.na(db_cat_vars$ISS), 0, NA) )

db_cat_vars$PROTOCOL %>% unique()
db_cat_vars$EMN02 <- ifelse(db_cat_vars$PROTOCOL=="EMN02",1, ifelse(!is.na(db_cat_vars$PROTOCOL), 0, NA) )
db_cat_vars$AMB <- ifelse(db_cat_vars$PROTOCOL=="AMB",1, ifelse(!is.na(db_cat_vars$PROTOCOL), 0, NA) )
db_cat_vars$BO2005 <- ifelse(db_cat_vars$PROTOCOL=="BO2005",1, ifelse(!is.na(db_cat_vars$PROTOCOL), 0, NA) )


# db_cat_vars$IgG %>% table(useNA="always")

cat_vars = (names(db_cat_vars))
cat_vars

import$`K/L` %>% table
i=3

res_df_cat <- data.frame()

for(i in c(1,11)){
  
print(i)
  
name <- cat_vars[i]
name
  
model <- gmodels::CrossTable(db_cat_vars$MMrisk_CLASSIFIER_ALL, db_cat_vars[[i]], fisher = T)

p.val <- model$fisher.ts$p.value %>% round(4)
p.val

res <- model$t %>% t %>% as.data.frame.matrix() %>% rownames_to_column()
res2<- cbind(name,res,p.val)

res2

res_df_cat <- rbind(res_df_cat, res2)


}

# import$MMrisk_CLASSIFIER_ALL %>% table
res_df_cat$perc_risk1 <- round(res_df_cat$risk1/131, 3)
res_df_cat$perc_risk2 <- round(res_df_cat$risk2/170, 3)
res_df_cat$perc_risk3 <- round(res_df_cat$risk3/212, 3)

table(import$MMrisk_CLASSIFIER_ALL, import$Sex)


```

```{r}
write_tsv(res_df_cat, "clipboard")
```




______ SURVIVAL ANALYSYS ________

```{r}

library(survival)
library(survminer)

OS <- Surv( time = import$OS_months, event = import$OS_event_death)

PFS <- Surv( time = import$PFS_I_months, event = import$PFS_I_event)


```


OS
```{r}
ggsurvplot(survfit(OS ~ import$PROTOCOL, data = import), pval = T, risk.table = T, xlab = "OS")

coxph(OS ~ import$PROTOCOL, data = import) %>% summary

```

PFS
```{r}
ggsurvplot(survfit(PFS ~ import$PROTOCOL, data = import), pval = T, risk.table = T, xlab = "PFS")

coxph(OS ~ import$PROTOCOL, data = import) %>% summary

```
```{r}





```

