

GISTIC_2.0.result <- run.analysis(gp, 
                                  "urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00125:6.15.28", 
                                  refgene.file="Human_Hg19.mat", 
                                  seg.file="GISTIC_1q13_segm_Raw.txt", 
                                  markers.file="", 
                                  maxspace="10000", 
                                  array.list.file="", 
                                  cnv.file="DGV_gisticFormat%28Filters%3D100pts-0.05freq%29%2BCheckedNegativeControl_%282samp.min%29.txt", 
                                  gene.gistic="1", 
                                  amplifications.threshold="0.10", 
                                  deletions.threshold="0.10", 
                                  join.segment.size="50", 
                                  q-value.threshold="0.01", 
                                  remove.X="1", 
                                  cap.val="Inf", 
                                  confidence.level="0.95", 
                                  run.broad.analysis="1", 
                                  focal.length.cutoff="0.25", 
                                  max.sample.segs="1500", 
                                  arm.peel="1", 
                                  sample.center="median", 
                                  gene.collapse.method="extreme", 
                                  output.prefix="run2", 
                                  logdat="")